name: Renderizar e Publicar Horários

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Roda a cada 6 horas
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  pages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      # A autenticação do Google continua exatamente igual
      - name: Authenticate to Google Sheets
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: echo "$GOOGLE_CREDS" > gcreds.json
      
      # Esta é a nova parte: uma única ação para renderizar E publicar
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          # O arquivo exato que queremos renderizar
          target: horarios-2025-2.ipynb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
