name: Renderizar e Publicar Horários

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - main
      - master

# Define permissões para o job
permissions:
  contents: read
  pages: write      # Permissão para publicar no GitHub Pages
  id-token: write   # Permissão para autenticar a publicação

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Authenticate to Google Sheets
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: echo "$GOOGLE_CREDS" > gcreds.json

      # --- ETAPA DE RENDERIZAÇÃO MANUAL ---
      - name: Render Quarto Notebook
        run: quarto render horarios-2025-2.ipynb --to html

      # --- ETAPA DE PUBLICAÇÃO MANUAL ---
      # 1. Carrega o HTML gerado como um "artefato"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # O Quarto renderiza o .ipynb com o mesmo nome, mudando a extensão
          path: 'horarios-2025-2.html'
          
      # 2. Faz o deploy do artefato para o GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
